### ISSUE TITLE
The browser version didn't contain Class ActiveSelection

### ISSUE THREAD

**Issue by johnsoncheg** [jacob-beltran/fabric-browseronly#3]
## Version
1.7.16

## Expected Behavior
**Add Class`ActiveSelection` for the official fabric version contains `ActiveSelection`**
The Class `ActiveSelection` appears in fabric V2
## Actual Behavior
`console.log(fabric.ActiveSelection) ` ---> `undefined`

**Comment by jacob-beltran** [comment]
Just merged with latest upstream master and published new build
https://www.npmjs.com/package/fabric-browseronly

Please let me know if this fixes the issue.

**Comment by johnsoncheg** [comment]
@jacob-beltran  thanks dude. It works
